# Dependencies
markdown:         
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Half a mind
tagline:          'Science-y thoughts about learning and uncertainty'
description:      'Learning, decision making, and cognitive science.'
url:              http://dmarkant.github.io
#url:              http://127.0.0.1:4000
baseurl:          '/'
paginate:         5

author:
  name:           'Doug Markant'
  url:            https://twitter.com/dmarkant

# Custom vars
version:          1.0.0

github:
  repo:           

gems:             [jekyll-paginate]
