# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            half a mind
tagline:          'thoughts on the computational science of learning'
description:      'A place for thoughts on cognition, decision making, and learning.'
url:              http://dougmarkant.com
baseurl:          '/'
paginate:         5

author:
  name:           'Doug Markant'
  url:            https://twitter.com/dmarkant

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/dmarkant/dmarkant.github.io
