# Dependencies
markdown:         kramdown
highlighter:      

# Permalinks
permalink:        pretty

# Setup
title:            Of half a mind
tagline:          'Thoughts on learning and uncertainty'
description:      'Learning, decision making, and cognitive science.'
url:              http://www.dougmarkant.com
#url:              http://127.0.0.1:4000
baseurl:          '/'
#root:             '/'
paginate:         5

author:
  name:           'Doug Markant'
  url:            https://twitter.com/dmarkant

# Custom vars
version:          1.0.0

github:
  repo:           

plugins:          [jekyll-paginate]

kramdown: 
  parse_block_html: true
