# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Half a mind
tagline:          'Notes on the science of learning'
description:      'Thoughts on decision making, cognition, and learning.'
url:              http://dmarkant.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Doug Markant'
  url:            https://twitter.com/dmarkant

# Custom vars
version:          1.0.0

github:
  repo:           

gems:             [jekyll-paginate]
